MAIN_PAGE_CATEGORIES_BATCH_SIZE = 9

CATEGORY_PRODUCTS_BATCH_SIZE = 8

MAX_PRODUCT_PRICE_USD = 5000

PRODUCTS_COLORS = [
    ("#FFEDDA", "white"),
    ("#E4717A", "red"),
    ("#FCE883", "yellow"),
    ("#A8E4A0", "green"),
    ("#AFDAFC", "blue"),
    ("#CCCCFF", "purple"),
    ("#222222", "black")
]

PRODUCTS_STORTAGE_SIZES = [(1, 64), (2, 128), (3, 256), (4, 512), (5, 1024)]

MINIMUM_PHOTO_RESOLUTION_WIDTH = 300

MINIMUM_PHOTO_RESOLUTION_HEIGHT = 300

MAXIMUM_PHOTO_RESOLUTION_WIDTH = 4500

MAXIMUM_PHOTO_RESOLUTION_HEIGHT = 5000

USERNAME_PROFILE_FIELD_NAME = "username"

EMAIL_PROFILE_FIELD_NAME = "email"

AVATAR_PROFILE_FIELD_NAME = "avatar"

AVAILABLE_FOR_CHANGE_PROFILE_FIELDS = (
    USERNAME_PROFILE_FIELD_NAME,
    EMAIL_PROFILE_FIELD_NAME,
    AVATAR_PROFILE_FIELD_NAME
)
